project:
  type: website
  output-dir: docs

bibliography: references/open-data.bib    

website:
  title: "Introduction to Open Data"
  favicon: android-chrome-512x512.png
  open-graph: true
  twitter-card: true
  site-url: "https://julsraemy.ch/intro-open-data"
  repo-url: "https://github.com/julsraemy/intro-open-data"
  issue-url: "https://github.com/julsraemy/intro-open-data/issues/new/choose"
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  
  navbar:
    logo: logo-open.svg
    background: primary
    search: true
    tools:
      - icon: github
        url: https://github.com/julsraemy/intro-open-data
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - text: Exercises
        menu:
          - text: "Exercise 1: OA Deep Dive"
            file: exercises/ex-01.qmd
          - text: "Exercise 2: Up do date with Linked Data"
            file: exercises/ex-02.qmd
          - text: "Exercise 3: Movements and Principles"
            file: exercises/ex-03.qmd
          - text: "Exercise 4: Comparing ORD Platforms"
            file: exercises/ex-04.qmd
          - text: "Exercise 5: The Reuser's Perspective (OGD)"
            file: exercises/ex-05.qmd
          - text: "Exercise 6: Reading Assignment"
            file: exercises/ex-06.qmd
          - text: "Exercise 7: Open Refine"
            file: exercises/ex-07.qmd
          - text: "Exercise 8: IIIF & ML"
            file: exercises/ex-08.qmd
      - text: "Course Sections"
        menu:
          - text: "Characteristics of Open Data"
            file: sections/characteristics.qmd
          - text: "Associated Movements"
            file: sections/movements.qmd
          - text: "Associated Principles"
            file: sections/principles.qmd
          - text: "Open Data Platforms and Organisations"
            file: sections/platforms.qmd
          - text: "Assessment, Data Quality, and Best Practices"
            file: sections/assessment.qmd
          - text: "Techniques, Software, and Tools"
            file: sections/techniques.qmd
          - text: "Showcases"
            file: sections/showcases.qmd
      - href: references.qmd
        text: References
      - href: about.qmd
        text: About
  
  sidebar:
    - title: "Course Navigation"
      contents:
        - sections/characteristics.qmd
        - sections/movements.qmd
        - sections/principles.qmd
        - sections/platforms.qmd
        - sections/assessment.qmd
        - sections/techniques.qmd
        - sections/showcases.qmd
  
  page-footer:
    left: "Julien A. Raemy | Introduction to Open Data" 
    right: "Content is published under a Creative Commons Attribution 4.0 International licence"
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles/custom.scss
    code-line-numbers: true
    code-link: true
    code-fold: true
    link-external-icon: true
    link-external-newwindow: true
    page-layout: full
    highlight-style: github
    toc: true
    toc-depth: 5
    csl: https://www.zotero.org/styles/apa
    bibliography-location: document
  